# Build targets for indexing utilities.
load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "text_format",
    srcs = ["text_format.py"],
    visibility = ["//visibility:public"],
)
