# proto-file: indexing/config/bundle.proto
# proto-message: ProjectBundle

bundle_name: "aadc"

# go/keep-sorted start
input: {
  directory: "ads/ai/aadc/"
}

input: {
  directory: "ads/ai/training/workflow/aadc_demographics_batch"
}

input: {
  directory: "ads/ai/training/workflow/aadc_demographics_batch_xmanager"
}

input: {
  directory: "configs/file/placer/aadc-demographics-storage"
}

input: {
  directory: "production/borg/aadc-demographics"
}

input: {
  directory: "production/security/bclid/demographics"
}
# go/keep-sorted end
