# proto-file: indexing/config/bundle.proto
# proto-message: ProjectBundle

bundle_name: "aadc"

input: {
  directory: "src/ai/core/"
}

input: {
  directory: "src/training/workflows/batch/"
}

input: {
  directory: "src/training/workflows/config/"
}

input: {
  directory: "config/storage/"
}

input: {
  directory: "infra/k8s/"
}

input: {
  directory: "infra/security/"
}
