# Build targets for indexing configurations.
load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "bundle_pb2",
    srcs = ["bundle_pb2.py"],
    visibility = ["//visibility:public"],
)
